### ISSUE TITLE
dist/src/index.js

### ISSUE THREAD

**Issue by neofitik** [j-o-d-o/multiplayer-babylon-js-game#1]
I do not find the "server/dist/src/index.js" file

**Comment by j-o-d-o** [comment]
Hi, you need to install typescript:
```>>npm install -g typescript```
and in then transpile the typescript code to javascript with (while being in the server folder)
```>>tsc```

**Comment by neofitik** [comment]
Sorry, but i have error:


src/controller.ts(22,51): error TS2345: Argument of type '{ initial: States.CONNECTING_TO_SERVER; events: [{ name: Events.CONNECTED; from: States.CONNECTIN...' is not assignable to parameter of type 'StateMachineConfig<States, Events>'.
  Types of property 'events' are incompatible.
    Type '[{ name: Events.CONNECTED; from: States.CONNECTING_TO_SERVER; to: States.LOADING_GAME; }, { name:...' is not assignable to type '[{ name: Events; from: States | States[]; to: States; }]'.
      Types of property 'length' are incompatible.
        Type '3' is not assignable to type '1'.

**Comment by j-o-d-o** [comment]
I took a fresh clone and followed the instructions on the readme and I can't reproduce your error :/
The error in the browser is of course because there already was an error in transpiling typescript.

**Comment by neofitik** [comment]
Thanks for the answer.
